version: '2'

services:
  mysql-5.5.57:
    image: "mysql:5.5.57"
    container_name: mysql-5.5.57
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=123
    ports:
      - 127.0.0.1:3306:3306
    volumes:
      - mysql-store:/var/lib/mysql
    restart: unless-stopped
    network_mode: host

volumes:
  mysql-store:

